language: node_js
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
services:
  - postgresql
  - redis-server
cache:
  directories:
    - node_modules
node_js:
  - lts/*
  - node
before_script:
  - createdb travis_miniverse_test_1
  - PGDATABASE=travis_miniverse_test_1 npx db-migrate up
script:
  - npm test -- -w 1
