language: node_js
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        postgresql: 9.6
    - os: linux
      dist: trusty
      sudo: false
      addons:
        postgresql: 9.5
    - os: linux
      dist: trusty
      sudo: false
      addons:
        postgresql: 9.4
    - os: linux
      dist: trusty
      sudo: false
      addons:
        postgresql: 9.3
    - os: osx
      before_install:
        - brew install redis
      before_script:
        - mkdir $HOME/postgres
        - initdb -D $HOME/postgres
        - pg_ctl -D $HOME/postgres start
        - createuser
        - redis-server --daemonize yes
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
services:
  - redis-server
cache:
  directories:
    - node_modules
node_js:
  - lts/*
  - node
before_script:
  - createdb travis_miniverse_test_1
  - PGDATABASE=travis_miniverse_test_1 npx db-migrate up
script:
  - npm test -- -w 1
