language: node_js
node_js: node
stages:
  - test
  - name: deploy
    if: branch = master
jobs:
  include:
  - &job_test_linux_100
    stage: test
    os: linux
    dist: xenial
    sudo: false
    addons:
      postgresql: 10
    env:
      - AWS_ENDPOINT=http://127.0.0.1:9000
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=miniostorage
      - AWS_SIGNATURE_VERSION=v4
      - AWS_S3_BUCKET=miniverse
      - AWS_S3_FORCE_PATH_STYLE=1
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=miniostorage
  - <<: *job_test_linux_100
    addons:
      postgresql: 9.6
  - <<: *job_test_linux_100
    addons:
      postgresql: 9.5
  - <<: *job_test_linux_100
    addons:
      postgresql: 9.6
    dist: trusty
  - <<: *job_test_linux_100
    addons:
      postgresql: 9.5
    dist: trusty
  - <<: *job_test_linux_100
    os: osx
    before_install:
      - initdb -D "$HOME/postgres"
      - pg_ctl -D "$HOME/postgres" start
      - brew install minio redis
      - minio server travis/minio.RELEASE.2018-07-23T18-34-49Z/srv/data &
      - redis-server --daemonize yes
      - pg_isready
    cache:
      directories:
        - node_modules
        - "$HOME/Library/Caches/Homebrew"
  - stage: deploy
    os: linux
    dist: xenial
    sudo: false
    addons:
      apt:
        packages:
          - awscli
    script:
      - npm pack
      - mv miniverse-0.0.1.tgz docker
      - docker build -t miniorg/miniverse docker
      - docker login -p "$DOCKER_PASSWORD" -u "$DOCKER_USER"
      - docker push miniorg/miniverse
      - pip install --user awscli
      - aws ecs update-service --force-new-deployment --service server
services:
  - redis-server
cache:
  directories:
    - node_modules
    - travis/minio.RELEASE.2019-04-04T18-31-46Z/bin
before_install:
  - |
    if [ ! -f travis/minio.RELEASE.2019-04-04T18-31-46Z/bin/minio ]
    then
      mkdir -p travis/minio.RELEASE.2019-04-04T18-31-46Z/bin
      wget https://dl.minio.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2019-04-04T18-31-46Z -O travis/minio.RELEASE.2019-04-04T18-31-46Z/bin/minio
      sha1sum -c <<< '06ad2f55f370d2ad1d1310cbdcae8889637a8eb1  travis/minio.RELEASE.2019-04-04T18-31-46Z/bin/minio'
      chmod a+x travis/minio.RELEASE.2019-04-04T18-31-46Z/bin/minio
    fi
  - ./travis/minio.RELEASE.2019-04-04T18-31-46Z/bin/minio server travis/minio.RELEASE.2019-04-04T18-31-46Z/srv/data &
script:
  - npx tsc -p browser.tsconfig.json
  - npx tsc -p node.tsconfig.json
  - npx tsc -p test.tsconfig.json
  - createdb travis_test_1
  - PGDATABASE=travis_test_1 npx db-migrate up
  - node travis/create-bucket.js
  - npm test -- -w 1
