stages:
  - name: deploy
    if: branch = master
language: node_js
jobs:
  include:
  - stage: deploy
    os: linux
    dist: trusty
    script: echo hello
    sudo: false
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        postgresql: 9.6
    - os: linux
      dist: trusty
      sudo: false
      addons:
        postgresql: 9.5
    - os: linux
      dist: trusty
      sudo: false
      addons:
        postgresql: 9.4
    - os: linux
      dist: trusty
      sudo: false
      addons:
        postgresql: 9.3
    - os: osx
      before_install:
        - initdb -D $HOME/postgres
        - pg_ctl -D $HOME/postgres start
        - brew install redis
        - redis-server --daemonize yes
        - pg_isready
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
services:
  - redis-server
cache:
  directories:
    - node_modules
node_js:
  - lts/*
  - node
before_script:
  - createdb travis_miniverse_test_1
  - PGDATABASE=travis_miniverse_test_1 npx db-migrate up
script:
  - npm test -- -w 1
