language: node_js
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      services:
        - postgresql
        - redis-server
    - os: osx
      before_install:
        - brew install redis
      before_script:
        - pg_ctl -D /usr/local/var/postgres start
        - redis-server --daemonize
cache:
  directories:
    - node_modules
node_js:
  - lts/*
  - node
before_script:
  - createdb travis_miniverse_test_1
  - PGDATABASE=travis_miniverse_test_1 npx db-migrate up
script:
  - npm test -- -w 1
